from flask import Flask, jsonify, render_template

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

# A sample data structure. In the future, this will be generated by your scripts.
sample_weekly_data = {
    "year": 2024,
    "week": 8,
    "game_of_the_week": {
        "manager1": "Team A",
        "manager2": "Team B",
        "streak1": "W2",
        "streak2": "L1",
        "projection": "115.4 - 112.8"
    },
    "matchups": [
        {
            "manager1": "Team C",
            "manager2": "Team D",
            "streak1": "W4",
            "streak2": "W1",
            "projection": "120.1 - 105.5"
        },
        {
            "manager1": "Team E",
            "manager2": "Team F",
            "streak1": "L3",
            "streak2": "L2",
            "projection": "98.7 - 101.3"
        }
    ],
    "commissioner_notes": "This is a sample note from the commissioner for Week 8."
}

@app.route('/api/week/<int:year>/<int:week>')
def get_week_data(year, week):
    # For now, we'll ignore the year and week and return the sample data.
    # In the future, you would use these parameters to fetch the correct data.
    return jsonify(sample_weekly_data)

if __name__ == '__main__':
    app.run(debug=True, port=5001)
